# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TIZsGFSy6qTR7y44R_ZKxK2_u9M0YUG

Create three different strings
"""

single_quote = 'This is a string in single quotes'
double_quote = "This is a string in double quotes"
triple_quote = """This is a string in triple quotes"""

"""String with both single and double quotes"""

quote = 'She said, "I\'m going to the store."'
print(quote)

"""Multi-line string about a hobby"""

hobby = """I enjoy playing games okay? bye.
It allows me to express my creativity.
I mostly paint landscapes and abstract art."""
print(hobby)

"""Manipulate full name"""

full_name = "john doe"
print(full_name.upper())
print(full_name.lower())
print(full_name.title())

"""Clean up messy text"""

messy_text = "  Python programming is fun!  "
clean_text = messy_text.strip()
replaced_text = clean_text.replace("fun", "amazing")
i_count = clean_text.count("i")
print(clean_text)
print(replaced_text)
print(f"Occurrences of 'i': {i_count}")

"""Sentence operations"""

sentence = "The quick brown fox jumps over the lazy dog"
words = sentence.split()
joined = "-".join(words)
starts_with_the = sentence.startswith("The")
fox_position = sentence.find("fox")
print(words)
print(joined)
print(f"Starts with 'The'? {starts_with_the}")
print(f"Position of 'fox': {fox_position}")

"""F-Strings"""

your_name = "samad bengali"
your_age = 18
language = "Python"

print(f"My name is {your_name} and I am {your_age} years old.")
print(f"I enjoy programming in {language}, it's my favorite!")
print(f"In 5 years, I will be {your_age + 5} years old.")

"""Combining String Methods with F-Strings"""

# Inputs
first = input("Enter your first name: ").strip().capitalize()
last = input("Enter your last name: ").strip().capitalize()
birth_year = input("Enter your birth year: ").strip()

# Calculate age
from datetime import datetime
current_year = datetime.now().year
age = current_year - int(birth_year)

# Create username
username = first[0].lower() + last.lower() + birth_year

# Profile message
print(f"Profile: {first} {last}, Age: {age}, Username: {username}")